const sectionOrganisms = {
    animals: [
        { common: 'Human', scientific: 'Homo sapiens' },
        { common: 'Atlantic Cod', scientific: 'Gadus morhua' },
        { common: 'Housefly', scientific: 'Musca domestica' },
        { common: 'Earthworm', scientific: 'Lumbricus terrestris' },
        { common: 'Mosquito', scientific: 'Anopheles gambiae' },
        { common: 'Honeybee', scientific: 'Apis mellifera' },
        { common: 'Frog', scientific: 'Rana temporaria' },
        { common: 'Zebrafish', scientific: 'Danio rerio' },
        { common: 'Snail', scientific: 'Cornu aspersum' },
        { common: 'Woodlouse', scientific: 'Oniscus asellus' },
        { common: 'Pigeon', scientific: 'Columba livia' },
        { common: 'European Rabbit', scientific: 'Oryctolagus cuniculus' },
        { common: 'Brown Rat', scientific: 'Rattus norvegicus' },
        { common: 'Cow', scientific: 'Bos taurus' },
        { common: 'Sheep', scientific: 'Ovis aries' },
        { common: 'Goat', scientific: 'Capra hircus' },
        { common: 'Chicken', scientific: 'Gallus gallus' },
        { common: 'Pig', scientific: 'Sus scrofa domesticus' },
        { common: 'Cat', scientific: 'Felis catus' },
        { common: 'Dog', scientific: 'Canis lupus' },
        { common: 'Fruit Fly', scientific: 'Drosophila melanogaster' },
        { common: 'Ladybug', scientific: 'Coccinella septempunctata' },
        { common: 'Grasshopper', scientific: 'Chorthippus brunneus' },
        { common: 'Butterfly', scientific: 'Papilio machaon' },
        { common: 'Moth', scientific: 'Bombyx mori' },
        { common: 'Newt', scientific: 'Triturus cristatus' },
        { common: 'Stag Beetle', scientific: 'Lucanus cervus' },
        { common: 'Garden Spider', scientific: 'Araneus diadematus' },
        { common: 'Pill Millipede', scientific: 'Glomeris marginata' },
        { common: 'Red Fox', scientific: 'Vulpes vulpes' },
        { common: 'European Badger', scientific: 'Meles meles' },
        { common: 'European Hedgehog', scientific: 'Erinaceus europaeus' },
        { common: 'Grey Squirrel', scientific: 'Sciurus carolinensis' },
        { common: 'Red Squirrel', scientific: 'Sciurus vulgaris' },
        { common: 'European Robin', scientific: 'Erithacus rubecula' },
        { common: 'Mallard', scientific: 'Anas platyrhynchos' },
        { common: 'Mute Swan', scientific: 'Cygnus olor' },
        { common: 'Barn Owl', scientific: 'Tyto alba' },
        { common: 'Goldfish', scientific: 'Carassius auratus' },
        { common: 'Common Carp', scientific: 'Cyprinus carpio' },
        { common: 'Great White Shark', scientific: 'Carcharodon carcharias' },
        { common: 'Atlantic Salmon', scientific: 'Salmo salar' },
        { common: 'Seahorse', scientific: 'Hippocampus hippocampus' },
        { common: 'Common Octopus', scientific: 'Octopus vulgaris' },
        { common: 'Common Dolphin', scientific: 'Delphinus delphis' },
        { common: 'Porpoise', scientific: 'Phocoena phocoena' },
        { common: 'Killer Whale', scientific: 'Orcinus orca' },
        { common: 'Humpback Whale', scientific: 'Megaptera novaeangliae' },
        { common: 'Turtle', scientific: 'Chelonia mydas' },
        { common: 'Emperor Penguin', scientific: 'Aptenodytes forsteri' },
        { common: 'Bald Eagle', scientific: 'Haliaeetus leucocephalus' },
        { common: 'Iberian Lynx', scientific: 'Lynx pardinus' },
        { common: 'Red Deer', scientific: 'Cervus elaphus' },
        { common: 'Wild Boar', scientific: 'Sus scrofa' },
        { common: 'European Hake', scientific: 'Merluccius merluccius' },
        { common: 'Common Blackbird', scientific: 'Turdus merula' },
        { common: 'Great Scallop (Vieira)', scientific: 'Pecten maximus' },
        { common: 'Fire Salamander', scientific: 'Salamandra salamandra' },
        { common: 'House Sparrow', scientific: 'Passer domesticus' },
        { common: 'Common Wall Lizard', scientific: 'Podarcis muralis' },
        { common: 'Mediterranean Mussel', scientific: 'Mytilus galloprovincialis' },
        { common: 'European Otter', scientific: 'Lutra lutra' },
        { common: 'Griffon Vulture', scientific: 'Gyps fulvus' },
        { common: 'Common Kestrel', scientific: 'Falco tinnunculus' },
        { common: 'Common Toad', scientific: 'Bufo bufo' },
        { common: 'European Hare', scientific: 'Lepus europaeus' },
        { common: 'Eurasian Jay', scientific: 'Garrulus glandarius' },
        { common: 'Grass Snake', scientific: 'Natrix natrix' },
        { common: 'Axolotl', scientific: 'Ambystoma mexicanum' },
        { common: 'European Sardine', scientific: 'Sardina pilchardus' },
        { common: 'Atlantic Horse Mackerel', scientific: 'Trachurus trachurus' },
        { common: 'Ant', scientific: 'Lasius niger' },
        { common: 'Termite', scientific: 'Reticulitermes flavipes' },
        { common: 'Nematode/Roundworm', scientific: 'Caenorhabditis elegans' },
        { common: 'Copepod', scientific: 'Calanus finmarchicus' },
        { common: 'Antarctic Krill', scientific: 'Euphausia superba' },
        { common: 'Springtail', scientific: 'Folsomia candida' },
        { common: 'Mite', scientific: 'Tetranychus urticae' },
        { common: 'Zooplankton', scientific: 'Daphnia magna' },
        { common: 'Silverfish', scientific: 'Lepisma saccharinum' },
        { common: 'Cockroach', scientific: 'Blattella germanica' },
        { common: 'Beetle', scientific: 'Carabus nemoralis' },
        { common: 'Tick', scientific: 'Ixodida' },
        { common: 'Flea', scientific: 'Siphonaptera' },
        { common: 'Aphid', scientific: 'Acyrthosiphon pisum' },
        { common: 'Cricket', scientific: 'Acheta domesticus' },
        { common: 'Clam', scientific: 'Mya arenaria' },
        { common: 'Sea Urchin', scientific: 'Paracentrotus lividus' },
        { common: 'Jellyfish', scientific: 'Aurelia aurita' },
        { common: 'Tardigrade/Water Bear', scientific: 'Milnesium tardigradum' },
        { common: 'Barnacles', scientific: 'Semibalanus balanoides' },
        { common: 'Shrimp', scientific: 'Crangon crangon' },
        { common: 'Sea Cucumber', scientific: 'Holothuroidea' },
        { common: 'Centipede', scientific: 'Chilopoda' },
        { common: 'Hydra', scientific: 'Hydra vulgaris' },
        { common: 'Anemone', scientific: 'Actiniaria' },
        { common: 'Coral', scientific: 'Anthozoa' },
        { common: 'Squid', scientific: 'Loligo vulgaris' },
        { common: 'Hagfish', scientific: 'Myxiniformes' },
        { common: 'Anchovy', scientific: 'Engraulis encrasicolus' },
        { common: 'Lanternfish', scientific: 'Myctophum punctatum' },
        { common: 'Dung Beetle', scientific: 'Scarabaeus sacer' },
        { common: 'Plankton', scientific: 'Skeletonema costatum' },
        { common: 'Bat', scientific: 'Pipistrellus pipistrellus' },
        { common: 'Bumblebee', scientific: 'Bombus terrestris' },
        { common: 'Hawk', scientific: 'Astur gentilis' },
        { common: 'Eagle', scientific: 'Aquila chrysaetos' },
        { common: 'Buzzard', scientific: 'Buteo buteo' }
    ],
    plants: [
        { common: 'Maize', scientific: 'Zea mays' },
        { common: 'Wheat', scientific: 'Triticum aestivum' },
        { common: 'Rice', scientific: 'Oryza sativa' },
        { common: 'Barley', scientific: 'Hordeum vulgare' },
        { common: 'Pea', scientific: 'Pisum sativum' },
        { common: 'Runner Bean', scientific: 'Phaseolus vulgaris' },
        { common: 'Sunflower', scientific: 'Helianthus annuus' },
        { common: 'Dandelion', scientific: 'Taraxacum officinale' },
        { common: 'Common Daisy', scientific: 'Bellis perennis' },
        { common: 'English Oak', scientific: 'Quercus robur' },
        { common: 'Mango Tree', scientific: 'Mangifera indica' },
        { common: 'Brazil Nut Tree', scientific: 'Bertholletia excelsa' },
        { common: 'Acacia Tree', scientific: 'Vachellia tortilis' },
        { common: 'Arctic Willow', scientific: 'Salix arctica' },
        { common: 'Water Lily', scientific: 'Nymphaea alba' },
        { common: 'Elodea', scientific: 'Elodea canadensis' },
        { common: 'Duckweed', scientific: 'Lemna minor' },
        { common: 'Tomato', scientific: 'Solanum lycopersicum' },
        { common: 'Potato', scientific: 'Solanum tuberosum' },
        { common: 'Arabidopsis', scientific: 'Arabidopsis thaliana' }
    ],
    fungi: [
        { common: 'Yeast', scientific: 'Saccharomyces cerevisiae' },
        { common: 'Mucor', scientific: 'Mucor mucedo' },
        { common: 'Rhizopus (Black bread mold)', scientific: 'Rhizopus stolonifer' },
        { common: 'Penicillium', scientific: 'Penicillium chrysogenum' },
        { common: 'Aspergillus', scientific: 'Aspergillus niger' },
        { common: 'Fly Agaric', scientific: 'Amanita muscaria' },
        { common: 'Oyster Mushroom', scientific: 'Pleurotus ostreatus' },
        { common: 'Button Mushroom', scientific: 'Agaricus bisporus' },
        { common: 'Candida', scientific: 'Candida albicans' },
        { common: 'Lichen (foliose)', scientific: 'Parmelia sulcata' }
    ],
    bacteria: [
        { common: 'Lactobacillus', scientific: 'Lactobacillus acidophilus' },
        { common: 'Pneumococcus', scientific: 'Streptococcus pneumoniae' },
        { common: 'Escherichia coli', scientific: 'Escherichia coli' },
        { common: 'Bacillus subtilis', scientific: 'Bacillus subtilis' },
        { common: 'Staphylococcus aureus', scientific: 'Staphylococcus aureus' },
        { common: 'Salmonella', scientific: 'Salmonella enterica' },
        { common: 'Mycobacterium tuberculosis', scientific: 'Mycobacterium tuberculosis' },
        { common: 'Helicobacter pylori', scientific: 'Helicobacter pylori' },
        { common: 'Rhizobium', scientific: 'Rhizobium leguminosarum' }
    ],
    protoctists: [
        { common: 'Chlorella', scientific: 'Chlorella vulgaris' },
        { common: 'Plasmodium', scientific: 'Plasmodium falciparum' },
        { common: 'Amoeba', scientific: 'Amoeba proteus' },
        { common: 'Paramecium', scientific: 'Paramecium caudatum' },
        { common: 'Euglena', scientific: 'Euglena gracilis' },
        { common: 'Volvox', scientific: 'Volvox aureus' },
        { common: 'Kelp', scientific: 'Macrocystis pyrifera' },
        { common: 'Sea Lettuce', scientific: 'Ulva lactuca' },
        { common: 'Bladderwrack', scientific: 'Fucus vesiculosus' }
    ]
};

window.sectionOrganisms = sectionOrganisms;
